// Relative, not aliased: nuxt.config.ts imports this module, and its import
// graph is resolved before Nuxt aliases exist.
import type { Tool, ToolCategory } from '../types/tools'

export const categoryLabels: Record<ToolCategory, string> = {
  data: 'Data Lab',
  crypto: 'Crypto Lab',
  color: 'Color Lab',
  network: 'Network Lab',
  image: 'Image Lab',
  dev: 'Dev Lab',
}

export const tools: Tool[] = [
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, minify, and validate JSON. Accepts JSON5 and JSONC input.',
    category: 'data',
    icon: 'i-lucide-braces',
    keywords: ['json', 'json5', 'jsonc', 'format', 'pretty', 'beautify', 'minify', 'validate', 'lint', 'compress', 'comments'],
    route: '/hub/data/json-formatter',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'json-to-typescript',
    slug: 'json-to-typescript',
    name: 'JSON → TypeScript',
    description: 'Convert JSON into TypeScript interfaces.',
    category: 'data',
    icon: 'i-lucide-file-type',
    keywords: ['json', 'typescript', 'interface', 'types'],
    route: '/hub/data/json-to-typescript',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'JSON to TypeScript Converter',
  },
  {
    id: 'json-yaml',
    slug: 'json-yaml',
    name: 'JSON ↔ YAML',
    description: 'Convert between JSON and YAML.',
    category: 'data',
    icon: 'i-lucide-arrow-left-right',
    keywords: ['json', 'yaml', 'yml', 'convert'],
    route: '/hub/data/converters/json-yaml',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'JSON to YAML Converter',
  },
  {
    id: 'json-toml',
    slug: 'json-toml',
    name: 'JSON ↔ TOML',
    description: 'Convert between JSON and TOML.',
    category: 'data',
    icon: 'i-lucide-arrow-left-right',
    keywords: ['json', 'toml', 'convert'],
    route: '/hub/data/converters/json-toml',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'JSON to TOML Converter',
  },
  {
    id: 'json-xml',
    slug: 'json-xml',
    name: 'JSON ↔ XML',
    description: 'Convert between JSON and XML.',
    category: 'data',
    icon: 'i-lucide-arrow-left-right',
    keywords: ['json', 'xml', 'convert'],
    route: '/hub/data/converters/json-xml',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'JSON to XML Converter',
  },
  {
    id: 'text-diff',
    slug: 'text-diff',
    name: 'Text Diff',
    description: 'Compare two texts and show the added, removed, and changed lines.',
    category: 'data',
    icon: 'i-lucide-git-compare',
    keywords: ['diff', 'compare', 'text', 'patch', 'unified'],
    route: '/hub/data/text-diff',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Text Diff Checker',
  },
  {
    id: 'lorem',
    slug: 'lorem',
    name: 'Lorem Ipsum & Mock Data',
    description: 'Generate placeholder paragraphs, words, or fake user profile JSON.',
    category: 'data',
    icon: 'i-lucide-text',
    keywords: ['lorem', 'ipsum', 'mock', 'fake', 'placeholder', 'users'],
    route: '/hub/data/lorem',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Lorem Ipsum Generator',
  },
  {
    id: 'markdown-studio',
    slug: 'markdown-studio',
    name: 'Markdown Live Studio',
    description: 'Write markdown with a real-time HTML preview and text metrics.',
    category: 'data',
    icon: 'i-lucide-file-text',
    keywords: ['markdown', 'md', 'gfm', 'html', 'preview', 'editor', 'live', 'word count'],
    route: '/hub/data/markdown-studio',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Markdown Editor with Live Preview',
  },
  {
    id: 'sql-formatter',
    slug: 'sql-formatter',
    name: 'SQL Query Formatter',
    description: 'Format, indent, and validate SQL queries across multiple dialects.',
    category: 'data',
    icon: 'i-lucide-database',
    keywords: ['sql', 'query', 'format', 'beautify', 'indent', 'validate', 'database', 'postgres', 'mysql', 'sqlite'],
    route: '/hub/data/sql-formatter',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'csv-json',
    slug: 'csv-json',
    name: 'CSV ↔ JSON / SQL',
    description: 'Convert CSV to JSON or SQL INSERT statements. Convert JSON arrays back to CSV.',
    category: 'data',
    icon: 'i-lucide-table',
    keywords: ['csv', 'json', 'sql', 'insert', 'delimiter', 'tsv', 'convert'],
    route: '/hub/data/converters/csv-json',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'CSV to JSON Converter',
  },
  {
    id: 'text-stats',
    slug: 'text-stats',
    name: 'Text Statistics',
    description: 'Count characters, words, sentences, reading time, and byte length.',
    category: 'data',
    icon: 'i-lucide-bar-chart-2',
    keywords: ['text', 'stats', 'word count', 'character count', 'reading time', 'analysis'],
    route: '/hub/data/text-stats',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Word Counter and Text Statistics',
  },
  {
    id: 'number-base',
    slug: 'number-base',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, and hexadecimal with big integer support.',
    category: 'data',
    icon: 'i-lucide-binary',
    keywords: ['number', 'base', 'binary', 'octal', 'decimal', 'hex', 'bigint', 'radix'],
    route: '/hub/data/number-base',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'env-json',
    slug: 'env-json',
    name: 'Env to JSON Converter',
    description: 'Convert .env configuration files to JSON format and convert JSON to .env format.',
    category: 'data',
    icon: 'i-lucide-file-code',
    keywords: ['env', 'dotenv', 'json', 'convert', 'environment', 'variables'],
    route: '/hub/data/env-json',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'unicode',
    slug: 'unicode',
    name: 'Unicode Inspector',
    description: 'Inspect Unicode code points, UTF-8 bytes, normalization forms, and hidden zero-width marks.',
    category: 'data',
    icon: 'i-lucide-search',
    keywords: ['unicode', 'utf8', 'utf16', 'code point', 'zero-width', 'character', 'normalize'],
    route: '/hub/data/unicode',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'yaml-validator',
    slug: 'yaml-validator',
    name: 'YAML Validator',
    description: 'Validate YAML syntax and inspect line numbers for errors.',
    category: 'data',
    icon: 'i-lucide-check-circle',
    keywords: ['yaml', 'yml', 'validator', 'lint', 'syntax', 'parse'],
    route: '/hub/data/yaml-validator',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'json-schema',
    slug: 'json-schema',
    name: 'JSON Schema Validator',
    description: 'Validate JSON data against JSON Schema specifications and find path errors.',
    category: 'data',
    icon: 'i-lucide-check-square',
    keywords: ['json', 'schema', 'validator', 'ajv', 'draft-07', 'validate'],
    route: '/hub/data/json-schema',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'table-viewer',
    slug: 'table-viewer',
    name: 'Table Viewer',
    description: 'View, sort, filter, and search CSV and JSON datasets in an interactive table.',
    category: 'data',
    icon: 'i-lucide-table-properties',
    keywords: ['table', 'csv', 'json', 'viewer', 'grid', 'sort', 'filter'],
    route: '/hub/data/table-viewer',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'CSV and JSON Table Viewer',
  },
  {
    id: 'fake-data',
    slug: 'fake-generator',
    name: 'Fake Data Generator',
    description: 'Generate realistic mock datasets with custom schema fields in JSON, CSV, or SQL formats.',
    category: 'data',
    icon: 'i-lucide-database',
    keywords: ['fake', 'mock', 'data', 'faker', 'generator', 'sql', 'csv', 'json', 'seed'],
    route: '/hub/data/fake-generator',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'hash',
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Hash text, a file, or a JSON object with SHA-256, SHA-512, MD5, CRC32, and more.',
    category: 'crypto',
    icon: 'i-lucide-hash',
    keywords: ['hash', 'sha', 'sha256', 'md5', 'digest', 'checksum', 'file', 'crc32', 'json', 'object hash', 'canonical', 'stable'],
    route: '/hub/crypto/hash-generator',
    clientOnly: false,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'encoder',
    slug: 'encoder',
    name: 'Encoder & Escaper',
    description: 'Encode and decode Base64, hex, URL, HTML entities, and language escapes.',
    category: 'dev',
    icon: 'i-lucide-binary',
    keywords: [
      'base64',
      'base64url',
      'encode',
      'decode',
      'hex',
      'hexadecimal',
      'url',
      'urlencode',
      'percent',
      'html',
      'entities',
      'escape',
      'unescape',
      'json',
      'sql',
      'shell',
      'codec',
    ],
    route: '/hub/dev/encoder',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Text Encoder and Escaper',
  },
  {
    id: 'generator',
    slug: 'generator',
    name: 'ID & Secret Generator',
    description: 'Generate UUIDs, ULIDs, NanoIDs, random strings, and passphrases.',
    category: 'crypto',
    icon: 'i-lucide-dices',
    keywords: [
      'uuid',
      'uuidv4',
      'uuidv7',
      'ulid',
      'nanoid',
      'id',
      'guid',
      'random',
      'string',
      'token',
      'api key',
      'passphrase',
      'diceware',
      'password',
      'secret',
      'generator',
    ],
    route: '/hub/crypto/generator',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Random ID and Secret Generator',
  },
  {
    id: 'password-benchmark',
    slug: 'password-benchmark',
    name: 'Password Benchmarker',
    description: 'Compare Argon2id and bcrypt hash timing with safe cost limits.',
    category: 'crypto',
    icon: 'i-lucide-key-round',
    keywords: ['password', 'argon2', 'bcrypt', 'hash', 'benchmark'],
    route: '/hub/crypto/password-benchmark',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'Argon2 and bcrypt Password Hash Benchmark',
  },
  {
    id: 'jwt',
    slug: 'jwt',
    name: 'JWT Debugger',
    description: 'Decode JWT header and payload. Verify HS256 signatures in the browser.',
    category: 'crypto',
    icon: 'i-lucide-shield-check',
    keywords: ['jwt', 'token', 'decode', 'hmac', 'hs256', 'exp'],
    route: '/hub/crypto/jwt',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'JWT Decoder and Debugger',
  },
  {
    id: 'hmac',
    slug: 'hmac',
    name: 'HMAC Generator',
    description: 'Sign messages using secret keys and Hash-based Message Authentication Codes.',
    category: 'crypto',
    icon: 'i-lucide-key',
    keywords: ['hmac', 'sha256', 'sha512', 'sign', 'hash', 'signature', 'mac'],
    route: '/hub/crypto/hmac',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'totp',
    slug: 'totp',
    name: 'TOTP 2FA Generator',
    description: 'Generate Time-based One-Time Passwords from Base32 secrets or otpauth URIs.',
    category: 'crypto',
    icon: 'i-lucide-clock',
    keywords: ['totp', '2fa', 'otp', 'authenticator', 'two factor', 'security', 'time-based'],
    route: '/hub/crypto/totp',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'aes',
    slug: 'aes',
    name: 'AES Encrypt & Decrypt',
    description: 'Encrypt and decrypt text with AES-256-GCM and PBKDF2 password derivation.',
    category: 'crypto',
    icon: 'i-lucide-shield-check',
    keywords: ['aes', 'encrypt', 'decrypt', 'gcm', 'pbkdf2', 'password', 'cipher'],
    route: '/hub/crypto/aes',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'AES-256 Encrypt and Decrypt',
  },
  {
    id: 'color-converter',
    slug: 'converter',
    name: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL, and OKLCH.',
    category: 'color',
    icon: 'i-lucide-palette',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'oklch'],
    route: '/hub/color/converter',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'contrast',
    slug: 'contrast-checker',
    name: 'Contrast Checker',
    description: 'Check the contrast ratio of two colors against the WCAG AA and AAA levels.',
    category: 'color',
    icon: 'i-lucide-contrast',
    keywords: ['contrast', 'a11y', 'wcag', 'accessibility'],
    route: '/hub/color/contrast-checker',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'WCAG Color Contrast Checker',
  },
  {
    id: 'palette',
    slug: 'palette-generator',
    name: 'Palette Generator',
    description: 'Generate lighter and darker color stops from one base color, then copy each HEX value.',
    category: 'color',
    icon: 'i-lucide-swatch-book',
    keywords: ['palette', 'colors', 'scheme'],
    route: '/hub/color/palette-generator',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Color Palette Generator',
  },
  {
    id: 'color-inspector',
    slug: 'inspector',
    name: 'Color Inspector',
    description: 'Inspect a color and read its HEX, RGB, HSL, and OKLCH channel values.',
    category: 'color',
    icon: 'i-lucide-pipette',
    keywords: ['color', 'inspect', 'picker'],
    route: '/hub/color/inspector',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'gradient-studio',
    slug: 'gradient-studio',
    name: 'CSS Gradient Studio',
    description: 'Create linear and radial CSS gradients with contrast checks.',
    category: 'color',
    icon: 'i-lucide-blend',
    keywords: ['css', 'gradient', 'linear', 'radial', 'color', 'stops', 'contrast'],
    route: '/hub/color/gradient-studio',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'CSS Gradient Generator',
  },
  {
    id: 'tailwind-shades',
    slug: 'tailwind-shades',
    name: 'Tailwind Shade Generator',
    description: 'Generate complete 50 to 950 color shade scales in Tailwind CSS format.',
    category: 'color',
    icon: 'i-lucide-palette',
    keywords: ['tailwind', 'color', 'shades', 'palette', 'css', 'generator', 'scale'],
    route: '/hub/color/tailwind-shades',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Tailwind Color Shade Generator',
  },
  {
    id: 'image-palette',
    slug: 'palette-extractor',
    name: 'Image Palette Extractor',
    description: 'Extract dominant colors, color swatches, and hex codes from uploaded images.',
    category: 'color',
    icon: 'i-lucide-pipette',
    keywords: ['image', 'color', 'palette', 'extract', 'dominant', 'swatch', 'hex'],
    route: '/hub/color/palette-extractor',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'dns',
    slug: 'dns-lookup',
    name: 'DNS Lookup',
    description: 'Look up A, AAAA, CNAME, MX, NS, TXT, and CAA records for a domain.',
    category: 'network',
    icon: 'i-lucide-globe',
    keywords: ['dns', 'lookup', 'a', 'mx', 'txt'],
    route: '/hub/network/dns-lookup',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'DNS Record Lookup',
  },
  {
    id: 'email-health',
    slug: 'email-health',
    name: 'Email Health Inspector',
    description: 'Inspect SPF, DKIM, DMARC, and MX routing for a domain.',
    category: 'network',
    icon: 'i-lucide-mail-check',
    keywords: ['email', 'spf', 'dkim', 'dmarc', 'mx', 'dns', 'health', 'deliverability'],
    route: '/hub/network/email-health',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'SPF, DKIM, and DMARC Checker',
  },
  {
    id: 'http-inspector',
    slug: 'http-inspector',
    name: 'HTTP Inspector',
    description: 'Read the response headers, the security report, and the redirect chain of a URL.',
    category: 'network',
    icon: 'i-lucide-list-tree',
    keywords: [
      'http',
      'headers',
      'response',
      'redirect',
      'location',
      'cors',
      'csp',
      'hsts',
      'security',
      'x-frame-options',
      'preflight',
    ],
    route: '/hub/network/http-inspector',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'HTTP Headers and Redirect Checker',
  },
  {
    id: 'url-inspector',
    slug: 'url-inspector',
    name: 'URL Inspector',
    description: 'Parse a URL into its protocol, host, path, hash, and query parameters.',
    category: 'network',
    icon: 'i-lucide-link',
    keywords: ['url', 'uri', 'parse', 'inspect'],
    route: '/hub/network/url-inspector',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'URL Parser and Inspector',
  },
  {
    id: 'og-preview',
    slug: 'og-preview',
    name: 'OpenGraph Previewer',
    description: 'Preview how a page may look when shared on social platforms.',
    category: 'network',
    icon: 'i-lucide-share-2',
    keywords: ['opengraph', 'og', 'twitter', 'meta', 'social', 'preview'],
    route: '/hub/network/og-preview',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'Open Graph and Social Preview',
  },
  {
    id: 'cidr',
    slug: 'cidr',
    name: 'CIDR Subnet Calculator',
    description: 'Calculate IPv4 subnet masks, network addresses, broadcast IPs, and usable host counts.',
    category: 'network',
    icon: 'i-lucide-network',
    keywords: ['cidr', 'subnet', 'ip', 'network', 'mask', 'broadcast', 'hosts'],
    route: '/hub/network/cidr',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'user-agent',
    slug: 'user-agent',
    name: 'User Agent Parser',
    description: 'Parse User Agent strings into browser, operating system, and device details.',
    category: 'network',
    icon: 'i-lucide-laptop',
    keywords: ['user agent', 'ua', 'browser', 'os', 'device', 'bot', 'parse'],
    route: '/hub/network/user-agent',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'cookie-inspector',
    slug: 'cookie-inspector',
    name: 'Cookie Inspector',
    description: 'Parse a Set-Cookie header and check Secure, HttpOnly, SameSite, the prefixes, and the lifetime.',
    category: 'network',
    icon: 'i-lucide-cookie',
    keywords: ['cookie', 'set-cookie', 'parser', 'httponly', 'secure', 'samesite', 'header', 'session', 'expires', 'max-age'],
    route: '/hub/network/cookie-inspector',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Set-Cookie Header Parser and Checker',
  },
  {
    id: 'ip-info',
    slug: 'ip-info',
    name: 'IP Address Info',
    description: 'Inspect public IP addresses, reverse DNS hostnames, and network classifications.',
    category: 'network',
    icon: 'i-lucide-globe',
    keywords: ['ip', 'my ip', 'public ip', 'dns', 'ptr', 'reverse dns', 'address'],
    route: '/hub/network/ip-info',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'IP Address Lookup',
  },
  {
    id: 'tls-inspector',
    slug: 'tls-inspector',
    name: 'TLS Certificate Inspector',
    description: 'Inspect SSL/TLS certificate chains, SANs, cipher suites, and expiration warnings.',
    category: 'network',
    icon: 'i-lucide-shield-check',
    keywords: ['tls', 'ssl', 'certificate', 'https', 'san', 'chain', 'cipher', 'expire'],
    route: '/hub/network/tls-inspector',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'SSL Certificate Checker',
  },
  {
    id: 'rdap-lookup',
    slug: 'rdap-lookup',
    name: 'RDAP / WHOIS Lookup',
    description: 'Query domain and IP registration data, registrars, and status over standard RDAP endpoints.',
    category: 'network',
    icon: 'i-lucide-globe',
    keywords: ['rdap', 'whois', 'domain', 'ip', 'registration', 'registrar', 'nameservers'],
    route: '/hub/network/rdap-lookup',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'WHOIS and RDAP Domain Lookup',
  },
  {
    id: 'image-studio',
    slug: 'studio',
    name: 'Image Studio',
    description: 'Crop, resize, rotate, mirror, and convert an image in one pass.',
    category: 'image',
    icon: 'i-lucide-image',
    keywords: [
      'image',
      'convert',
      'converter',
      'resize',
      'resizer',
      'rotate',
      'flip',
      'mirror',
      'grayscale',
      'webp',
      'avif',
      'jpeg',
      'png',
      'compress',
      'optimize',
      'transform',
    ],
    route: '/hub/image/studio',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
  },
  {
    id: 'image-metadata',
    slug: 'metadata',
    name: 'EXIF & Metadata Inspector',
    description: 'Read EXIF, GPS, and text metadata in an image, then remove it in the browser or on the server.',
    category: 'image',
    icon: 'i-lucide-file-search',
    keywords: ['image', 'exif', 'metadata', 'privacy', 'gps', 'strip', 'clean', 'stripper', 'iptc', 'xmp'],
    route: '/hub/image/metadata',
    clientOnly: false,
    serverRequired: false,
    status: 'available',
    seoTitle: 'EXIF Viewer and Remover',
  },
  {
    id: 'svg-converter',
    slug: 'svg-converter',
    name: 'SVG to PNG / WebP',
    description: 'Convert SVG code or files to PNG or WebP at 1x, 2x, and 4x.',
    category: 'image',
    icon: 'i-lucide-vector-square',
    keywords: ['svg', 'png', 'webp', 'rasterize', 'convert', 'scale'],
    route: '/hub/image/svg-converter',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'SVG to PNG Converter',
  },
  {
    id: 'image-base64',
    slug: 'base64',
    name: 'Image to Base64',
    description: 'Convert images to Base64 data URIs and decode Base64 back to images.',
    category: 'image',
    icon: 'i-lucide-file-code',
    keywords: ['image', 'base64', 'data uri', 'encode', 'decode', 'img'],
    route: '/hub/image/base64',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Image to Base64 Converter',
  },
  {
    id: 'placeholder',
    slug: 'placeholder',
    name: 'Placeholder Image Generator',
    description: 'Create solid or gradient placeholder images with custom dimensions and text.',
    category: 'image',
    icon: 'i-lucide-box',
    keywords: ['image', 'placeholder', 'svg', 'dimensions', 'banner', 'mockup'],
    route: '/hub/image/placeholder',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'favicon-generator',
    slug: 'favicon-generator',
    name: 'Favicon Set Generator',
    description: 'Convert an image into all standard favicon sizes, ICO, site.webmanifest, and HTML tags in a ZIP download.',
    category: 'image',
    icon: 'i-lucide-file-image',
    keywords: ['favicon', 'ico', 'manifest', 'icon', 'apple-touch-icon', 'zip', 'generator'],
    route: '/hub/image/favicon-generator',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'Favicon Generator',
  },
  {
    id: 'semver',
    slug: 'semver',
    name: 'Semver Calculator',
    description: 'Test semver ranges, sort versions, and bump a release number.',
    category: 'dev',
    icon: 'i-lucide-git-branch',
    keywords: ['semver', 'version', 'npm', 'range', 'bump'],
    route: '/hub/dev/semver',
    clientOnly: false,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'cron',
    slug: 'cron',
    name: 'Cron Visualizer',
    description: 'Validate a cron expression, read it in plain words, and preview the next runs.',
    category: 'dev',
    icon: 'i-lucide-calendar-clock',
    keywords: ['cron', 'schedule', 'crontab', 'timezone'],
    route: '/hub/dev/cron',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'Cron Expression Visualizer',
  },
  {
    id: 'tar-explorer',
    slug: 'tar',
    name: 'Tar Explorer',
    description: 'List and extract the entries of a tar or tar.gz archive in the browser.',
    category: 'dev',
    icon: 'i-lucide-folder-archive',
    keywords: ['tar', 'gzip', 'archive', 'tarball', 'extract', 'untar', 'tgz'],
    route: '/hub/dev/tar',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Tar Archive Viewer and Extractor',
  },
  {
    id: 'transpiler',
    slug: 'transpiler',
    name: 'TS / JSX Transpiler',
    description: 'Transpile TypeScript and JSX to plain JavaScript with Bun.',
    category: 'dev',
    icon: 'i-lucide-code-xml',
    keywords: ['typescript', 'tsx', 'jsx', 'transpile', 'bun'],
    route: '/hub/dev/transpiler',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    seoTitle: 'TypeScript to JavaScript Transpiler',
  },
  {
    id: 'code-minifier',
    slug: 'code-minifier',
    name: 'Code Minifier and Beautifier',
    description: 'Minify and format JavaScript, TypeScript, HTML, CSS, and JSON.',
    category: 'dev',
    icon: 'i-lucide-minimize-2',
    keywords: ['minify', 'beautify', 'format', 'oxc', 'prettier', 'javascript', 'typescript', 'html', 'css', 'json'],
    route: '/hub/dev/code-minifier',
    clientOnly: false,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'ast-playground',
    slug: 'ast-playground',
    name: 'AST Playground and Resolver',
    description: 'Inspect ESTree ASTs and resolve module paths with OXC.',
    category: 'dev',
    icon: 'i-lucide-git-fork',
    keywords: ['ast', 'oxc', 'parser', 'resolver', 'estree', 'typescript', 'javascript', 'jsx'],
    route: '/hub/dev/ast-playground',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    name: 'RegEx Tester and Explainer',
    description: 'Test regular expressions, highlight matches, and explain tokens.',
    category: 'dev',
    icon: 'i-lucide-regex',
    keywords: ['regex', 'regexp', 'regular expression', 'match', 'capture', 'flags'],
    route: '/hub/dev/regex-tester',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    name: 'Case and Slug Converter',
    description: 'Convert text into camelCase, PascalCase, snake_case, kebab-case, and URL slugs.',
    category: 'dev',
    icon: 'i-lucide-case-sensitive',
    keywords: ['case', 'slug', 'camelcase', 'pascalcase', 'snakecase', 'kebabcase'],
    route: '/hub/dev/case-converter',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'timestamp',
    slug: 'timestamp',
    name: 'Timestamp Studio',
    description: 'Convert Unix timestamps to ISO 8601 strings and relative time descriptions.',
    category: 'dev',
    icon: 'i-lucide-clock',
    keywords: ['timestamp', 'date', 'unix', 'epoch', 'iso8601', 'time'],
    route: '/hub/dev/timestamp',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Unix Timestamp Converter',
  },
  {
    id: 'css-units',
    slug: 'css-units',
    name: 'CSS Unit Converter',
    description: 'Convert values between px, rem, em, vw, and vh.',
    category: 'dev',
    icon: 'i-lucide-ruler',
    keywords: ['css', 'units', 'px', 'rem', 'em', 'vw', 'vh', 'convert'],
    route: '/hub/dev/css-units',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'qr-code',
    slug: 'qr-code',
    name: 'QR Code Studio',
    description: 'Generate SVG QR codes for URLs, text, and Wi-Fi networks.',
    category: 'dev',
    icon: 'i-lucide-qr-code',
    keywords: ['qr', 'qrcode', 'wifi', 'svg', 'barcode'],
    route: '/hub/dev/qr-code',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'QR Code Generator',
  },
  {
    id: 'sqlite-studio',
    slug: 'sqlite-studio',
    name: 'SQLite Studio',
    description: 'Inspect, query, and edit SQLite databases in memory.',
    category: 'data',
    icon: 'i-lucide-database',
    keywords: ['sqlite', 'database', 'sql', 'query', 'table', 'editor'],
    route: '/hub/data/sqlite-studio',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'SQLite Database Viewer and Editor',
  },
  {
    id: 'chmod',
    slug: 'chmod',
    name: 'Chmod Calculator',
    description: 'Convert between octal numbers and symbolic file permissions.',
    category: 'dev',
    icon: 'i-lucide-shield-check',
    keywords: ['chmod', 'permissions', 'linux', 'unix', 'octal', 'symbolic'],
    route: '/hub/dev/chmod',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'markdown-table',
    slug: 'markdown-table',
    name: 'Markdown Table Generator',
    description: 'Build, format, and align Markdown tables with real-time output.',
    category: 'dev',
    icon: 'i-lucide-table',
    keywords: ['markdown', 'table', 'generator', 'grid', 'columns', 'align'],
    route: '/hub/dev/markdown-table',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'glob-tester',
    slug: 'glob-tester',
    name: 'Glob Tester',
    description: 'Test glob patterns against a list of file paths in real-time.',
    category: 'dev',
    icon: 'i-lucide-file-search',
    keywords: ['glob', 'pattern', 'regex', 'match', 'wildcard', 'path'],
    route: '/hub/dev/glob-tester',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'curl-to-code',
    slug: 'curl-converter',
    name: 'cURL to Code Converter',
    description: 'Convert cURL commands to Fetch, Axios, Python Requests, and Go.',
    category: 'dev',
    icon: 'i-lucide-terminal',
    keywords: ['curl', 'code', 'fetch', 'axios', 'python', 'go', 'convert', 'http'],
    route: '/hub/dev/curl-converter',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
  },
  {
    id: 'html-converter',
    slug: 'html-converter',
    name: 'HTML & SVG to JSX / Vue',
    description: 'Convert HTML or SVG markup into a React JSX or Vue component.',
    category: 'dev',
    icon: 'i-lucide-code-xml',
    keywords: [
      'html',
      'svg',
      'jsx',
      'react',
      'vue',
      'converter',
      'sfc',
      'style',
      'component',
      'icon',
    ],
    route: '/hub/dev/html-converter',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'HTML to React and Vue Converter',
  },

  // Variant entries. A variant renders the component of its parent with a
  // preset. It gives one search intent one URL, one title, and its own prose.
  // The sidebar and the category pages list the parent only.
  {
    id: 'uuid',
    slug: 'uuid',
    name: 'UUID Generator',
    description: 'Generate random UUID v4 and time-ordered UUID v7 values in the browser.',
    category: 'crypto',
    icon: 'i-lucide-fingerprint',
    keywords: ['uuid', 'guid', 'uuidv4', 'uuidv7', 'unique id', 'ulid', 'nanoid'],
    route: '/hub/crypto/uuid',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    variantOf: 'generator',
  },
  {
    id: 'passphrase',
    slug: 'passphrase',
    name: 'Passphrase Generator',
    description: 'Generate a diceware passphrase that is strong and easy to remember.',
    category: 'crypto',
    icon: 'i-lucide-key-round',
    keywords: ['passphrase', 'diceware', 'password', 'words', 'memorable', 'xkcd'],
    route: '/hub/crypto/passphrase',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    variantOf: 'generator',
  },
  {
    id: 'base64',
    slug: 'base64',
    name: 'Base64 Encoder & Decoder',
    description: 'Encode text to Base64, or decode Base64 to text. Supports the URL-safe alphabet.',
    category: 'dev',
    icon: 'i-lucide-binary',
    keywords: ['base64', 'base64url', 'encode', 'decode', 'btoa', 'atob', 'data url'],
    route: '/hub/dev/base64',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Base64 Encoder and Decoder',
    variantOf: 'encoder',
  },
  {
    id: 'url-encoder',
    slug: 'url-encoder',
    name: 'URL Encoder & Decoder',
    description: 'Percent-encode text for a URL, or decode an encoded URL to text.',
    category: 'dev',
    icon: 'i-lucide-link',
    keywords: ['url', 'percent', 'encode', 'decode', 'urlencode', 'query string', 'encodeURIComponent'],
    route: '/hub/dev/url-encoder',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    seoTitle: 'URL Encoder and Decoder',
    variantOf: 'encoder',
  },
  {
    id: 'image-resizer',
    slug: 'resizer',
    name: 'Image Resizer',
    description: 'Resize an image to an exact width and height, or to a social media preset.',
    category: 'image',
    icon: 'i-lucide-scaling',
    keywords: ['resize', 'image', 'width', 'height', 'scale', 'open graph', 'twitter banner', 'instagram'],
    route: '/hub/image/resizer',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    variantOf: 'image-studio',
  },
  {
    id: 'image-converter',
    slug: 'converter',
    name: 'Image Converter',
    description: 'Convert an image to WebP, AVIF, JPEG, or PNG with a quality setting.',
    category: 'image',
    icon: 'i-lucide-image',
    keywords: ['convert', 'png to webp', 'jpg to webp', 'jpeg to png', 'avif', 'webp', 'jpeg', 'png'],
    route: '/hub/image/converter',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    variantOf: 'image-studio',
  },
  {
    id: 'image-cropper',
    slug: 'cropper',
    name: 'Image Cropper',
    description: 'Crop an image with a visual crop box, then resize and convert it in one pass.',
    category: 'image',
    icon: 'i-lucide-crop',
    keywords: ['crop', 'cropper', 'cut', 'trim', 'aspect ratio', 'square', '16:9', 'avatar'],
    route: '/hub/image/cropper',
    clientOnly: false,
    serverRequired: true,
    status: 'available',
    variantOf: 'image-studio',
  },
  {
    id: 'exif-remover',
    slug: 'exif-remover',
    name: 'EXIF Remover',
    description: 'Remove EXIF, GPS, and other metadata from a photo. Byte for byte in the browser, or by a re-encode on the server.',
    category: 'image',
    icon: 'i-lucide-shield-off',
    keywords: ['exif', 'remove', 'strip', 'metadata', 'gps', 'location', 'privacy', 'photo', 'clean'],
    route: '/hub/image/exif-remover',
    clientOnly: false,
    serverRequired: false,
    status: 'available',
    seoTitle: 'Remove EXIF Data from a Photo',
    variantOf: 'image-metadata',
  },
  {
    id: 'html-to-jsx',
    slug: 'html-to-jsx',
    name: 'HTML to JSX Converter',
    description: 'Convert HTML markup into React JSX with renamed attributes and a style object.',
    category: 'dev',
    icon: 'i-lucide-code',
    keywords: ['html', 'jsx', 'tsx', 'react', 'className', 'convert', 'component'],
    route: '/hub/dev/html-to-jsx',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    variantOf: 'html-converter',
  },
  {
    id: 'svg-component',
    slug: 'svg-component',
    name: 'SVG to React Component',
    description: 'Convert an SVG icon into a React component that takes props.',
    category: 'dev',
    icon: 'i-lucide-shapes',
    keywords: ['svg', 'react', 'component', 'icon', 'jsx', 'svgr', 'convert'],
    route: '/hub/dev/svg-component',
    clientOnly: true,
    serverRequired: false,
    status: 'available',
    variantOf: 'html-converter',
  },
]

export function getToolById(id: string): Tool | undefined {
  return tools.find(tool => tool.id === id)
}

/** Every tool that is not a variant. Use it for counts and lists in the UI. */
export function getPrimaryTools(): Tool[] {
  return tools.filter(tool => !tool.variantOf)
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter(tool => tool.category === category && !tool.variantOf)
}

export function getAvailableTools(): Tool[] {
  return tools.filter(tool => tool.status === 'available')
}

export function searchTools(query: string): Tool[] {
  const normalized = query.trim().toLowerCase()
  if (!normalized) {
    return tools
  }

  return tools.filter((tool) => {
    const haystack = [
      tool.name,
      tool.description,
      tool.category,
      ...tool.keywords,
    ]
      .join(' ')
      .toLowerCase()

    return haystack.includes(normalized)
  })
}
